### ISSUE TITLE
`Page` ohne `Limit`Parameter gibt immer die ersten 10 Einträge zurück

### ISSUE THREAD

**Issue by johanneshoess** [coodoo-io/listing#10]
`Page` ohne `Limit`Parameter gibt immer die ersten 10 Einträge zurück auch wenn die Metadaten des Response die richtigen Indexe zwischen `startIndex` und `endIndex`anzeigen.

**Comment by laugen** [comment]
Ist nun in [1.4.8-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/coodoo/coodoo-listing/1.4.8-SNAPSHOT/) behoben.
