### ISSUE TITLE
If ListingParameters.limit is set to zero, possible division by zero in ListingParameters.getPage()

### ISSUE THREAD

**Issue by nkombouris** [coodoo-io/listing#11]
**current behavior**
With the introduction of limit = 0, in Snapshot 1.4.8,  its possible to run into a division by zero. 

```
      public Integer getPage() {
        if (page == null && limit != null && index != null) {
            int mod = index % limit;
            if (index == 0) {
                return ListingConfig.DEFAULT_PAGE;
            } else if (mod == 0) {
                return index / limit;
            }
            return (index / limit) + 1;
        } else if (page == null) {
            return ListingConfig.DEFAULT_PAGE;
        } else if (page < 1) {
            return ListingConfig.DEFAULT_PAGE;
        }
        return page;
    }
```

**expected behavior**
getPage() returns `ListingConfig.DEFAULT_PAGE` or current `page` when the limit is set to zer

**Comment by laugen** [comment]
Thank you for that hint, this is now fixed in the develop brach!
An updated [1.4.8-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/coodoo/coodoo-listing/1.4.8-SNAPSHOT/) is available.
