### ISSUE TITLE
Pagination-Fehler in Metadata

### ISSUE THREAD

**Issue by immobilien-zeitung** [coodoo-io/listing#12]
In MetaData.java, Zeile 67 wird ein falscher Wert für this.endIndex berechnet, bzw. die Prüfung in Zeile 68 ist falsch und müsste lauten:
if (endIndex < count) {

Das hat zur Folge, dass man nicht weiterblättern kann, auch wenn noch Ergebnisse da sind.

**Comment by immobilien-zeitung** [comment]
Eigentlich könnte man doch immer
this.endIndex = count.intValue();
setzen, oder?

**Comment by mkuehle** [comment]
Wir haben das genauer untersucht und es ist kein Fehler weil die Attribute `startIndex` und `endIndex` sich nur auf die aktuell angewählte Seite beziehen. Deswegen kann man auch nicht einfach `this.endIndex = count.intValue();` setzen weil die Bedeutung von diesen beiden Attributen anders ist. Evtl. hätte man sie direkt ein wenig besser benennen können.

Mit diesen Metadaten weiß man immer alle notwendigen Indexe:
Index für Start der Gesamtliste: 0
Index für Ende der Gesamtliste: `count`
Index für den Start der aktuellen Page: `startIndex`
Index für das Ende der aktuellen Page: `endIndex`

In der Doku ist das auch so angegeben:
![image](https://user-images.githubusercontent.com/1588566/98438925-000ba300-20ee-11eb-9049-6bece4d079a4.png)
