### ISSUE TITLE
Request: Change default limit value from 10 to 0

### ISSUE THREAD

**Issue by mkuehle** [coodoo-io/listing#14]
At the moment the default limit is 10 which is pretty low.

If no limit is given with ListingParameter Object the new limit should be 0 -> all listing entries.

The initial start is easier with all list entries given (default page=1 and limit=0). With this defaults the default constructor of ListingParameters can be used. If the list grows the need for pagination and limits starts and the frontend can provide the mandatory parameters 'page' and 'limit'. The defaults are no longer needed then.

**Comment by JPM84** [comment]
Zero ist not a good default, it can break the system. I vote for 20 as default.
Details why limits are needed from stackoverflow:
https://stackoverflow.com/questions/52348110/what-is-a-good-practice-for-pagination-using-page-number-limit-in-go

and this is how tthe gothub api handles it:
https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by mkuehle** [comment]
Not a bug

**Comment by mkuehle** [comment]
Not a bug
