### ISSUE TITLE
IllegalStateException ("Duplicate key...") in ListingQuery.addToWhereConstraint()

### ISSUE THREAD

**Issue by immobilien-zeitung** [coodoo-io/listing#5]
ListingQuery.addToWhereConstraint(), Zeile 99.
Der Collector wirft eine IllegalStateException ("Duplicate key..."), da die übergebene domainClass ein Member "id" hat, welches in der Elternklasse von domainClass ebenfalls vorkommt.

Mit Markus bereits besprochen.

**Comment by laugen** [comment]
Resolved in [Version 1.4.7](https://github.com/coodoo-io/coodoo-listing/blob/master/CHANGELOG.md#147-2018-10-19)
